### ISSUE TITLE
Satellite imagery at z17

### ISSUE THREAD

**Issue by pratikyadav** [osm-in/openstreetmap.in#10]
http://openstreetmap.in/#17/23.23040/77.46140

Satellite imagery layer appearing only at one zoom level which is 17.

cc @planemad

**Comment by planemad** [comment]
So satellite imagery is enabled from z17 onwards, but since imagery is not available from z18, its shows up blank.

Its time to migrate the style to GL, this is a `wontfix` for the current style.

**Comment by planemad** [comment]
^ @pratikyadav

**Comment by pratikyadav** [comment]
@planemad 
 the imagery is there at zoom 18
![screen shot 2016-03-04 at 11 41 19 am](https://cloud.githubusercontent.com/assets/12744420/13519447/0bf58304-e1fe-11e5-9776-72b20fd02522.png)
http://lxbarth.com/compare/?openstreetmap.1b68f018&lxbarth.map-n8gsdqn4#18/13.00299/77.53489

But yes, let's stay this closed as no need to fix this as "GL" is coming

**Comment by planemad** [comment]
@pratikyadav ah ok, it think it was intentional to only make it z17 to avoid showing ugly grey tiles when they were not available before.
