### ISSUE TITLE
Map is down

### ISSUE THREAD

**Issue by naveenpf** [osm-in/openstreetmap.in#21]
https://openstreetmap.in/#5/22.150/79.081

**Comment by naveenpf** [comment]
@batpad @geohacker

**Comment by naveenpf** [comment]
Should we try https://wiki.openstreetmap.org/wiki/Map_internationalization_(India)  ?
https://openmaptiles.org/languages/native/#0.87/0/0

We had a demo in our website. Should go with production. 

Either with Wikimedia maps or Openmaptiler ?

**Comment by geohacker** [comment]
Thank you for the ticket @naveenpf. This is because @planemad's mapbox access token is expired. We'll wait for him or @jinalfoflia to give us a new token.

**Comment by jinalfoflia** [comment]
>We'll wait for him or @jinalfoflia to give us a new token.

Here's the token: `pk.eyJ1IjoiamluYWxmb2ZsaWEiLCJhIjoiY2psejFtZG8wMWhnMjNwcGFqdTNjaGF2MCJ9.ZQVAZAw8Xtg4H2YSuG4PlA`


cc: @naveenpf @geohacker @planemad

**Comment by karthikb351** [comment]
Someone needs to do a redeploy since this doesn't seem to be running on GitHub Pages.
@geohacker @planemad?

**Comment by geohacker** [comment]
I just did a deploy.

**Comment by scaidermern** [comment]
`README.md` still mentions the old access token
`pk.eyJ1Ijoib3BlbnN0cmVldG1hcCIsImEiOiJhNVlHd29ZIn0.ti6wATGDWOmCnCYen-Ip7Q`
Please update it with
`pk.eyJ1IjoiamluYWxmb2ZsaWEiLCJhIjoiY2psejFtZG8wMWhnMjNwcGFqdTNjaGF2MCJ9.ZQVAZAw8Xtg4H2YSuG4PlA`

**Comment by karthikb351** [comment]
@scaidermern The README has been updated as well, good catch.

**Comment by jinalfoflia** [comment]
Hey everyone, this map is currently using an access token from my personal account. For better coordination, Mapbox has insisted on us creating an OSM India account and have them apply coupons for the same. It's an easier way to do as well as does not depend on individual accounts. Lesser chances of the map going down. 

@chtnha has an active OSM India email address that we use for the OSM-In twitter account, we'll create an OSM-In account in Mapbox Studio and have the access token from the same account. I'll make sure that a coupon is applied for the same from Mapbox's end. I'd love to hear what are everyone's thoughts on this. 

cc: @geohacker @naveenpf

**Comment by jinalfoflia** [comment]
Hey @geohacker here's the token from OSM India Mapbox account: `pk.eyJ1Ijoib3NtLWluIiwiYSI6ImNqcnVxMTNrNTJwbHc0M250anUyOW81MjgifQ.cZnvZEyWT5AzNeO3ajg5tg`

I'll coordinate with the team and get a coupon applied. Please let me know when you have changed the access token to this one. Thank you for helping here! 

If anyone needs access to the account, please let @chtnha or me know about it.

**Comment by vikram-gsu** [comment]
Thanks for the effort y'all. I'm using the layer for one of my projects. Just an update though: I couldn't get the current url on the readme page to work. This worked for me: 

`https://api.tiles.mapbox.com/v4/openstreetmap.1b68f018/{z}/{x}/{y}.png?access_token=pk.eyJ1Ijoib3NtLWluIiwiYSI6ImNqcnVxMTNrNTJwbHc0M250anUyOW81MjgifQ.cZnvZEyWT5AzNeO3ajg5tg`

(same tokens, but different url - not sure if it happened to anyone else)

**Comment by naveenpf** [comment]
Closing the ticket
