### ISSUE TITLE
Map metrics for OSM 

### ISSUE THREAD

**Issue by naveenpf** [osm-in/openstreetmap.in#23]
Please add next admin level in metrics for India

https://metrics.improveosm.org

https://wiki.openstreetmap.org/wiki/Districts_in_India (admin_level=5)

Connect with @Telenav

**Comment by planemad** [comment]
Will add a link to metrics in #36

Can use a 1 month stats link: https://metrics.improveosm.org/navigable-roads/total-metrics-per-interval?duration=weekly&locationType=country&locationId=99&unit=km&from=2020-09-04&to=2020-10-04
