### ISSUE TITLE
Taginfo  is down

### ISSUE THREAD

**Issue by naveenpf** [osm-in/openstreetmap.in#25]
Taginfo :- http://taginfo.openstreetmap.in/

**Comment by yogiks** [comment]
Hey Naveen, couple of gems were obsolete on the instance I was running. I had taken it down for an upgrade. Will get it back online soon.

**Comment by yogiks** [comment]
@naveenpf, taginfo is back online.

**Comment by naveenpf** [comment]
Fixed
