### ISSUE TITLE
Give attribution to OpenStreetMap and Mapbox

### ISSUE THREAD

**Issue by robinmetral** [osm-in/openstreetmap.in#27]
I just stumbled on your project after [a related question](https://help.openstreetmap.org/questions/66278/download-map-tiles-from-openstreetmapin) was asked on the OpenStreetMap help forums.

Having used Leaflet, I know that the default map comes with an OpenStreetMap attribution, which it is possible to remove, but shouldn't be.

You appear to have chosen to remove attribution from the map, except for the hardcoded Leaflet mention.

![capture du 2018-10-11 18-03-51](https://user-images.githubusercontent.com/35560568/46799836-119fe680-cd80-11e8-8372-bc625fcfadb3.png)

Don't you think that you should [give credit to OSM contributors](https://www.openstreetmap.org/copyright)? Also an [attribution to Mapbox](https://www.mapbox.com/help/how-attribution-works/), on whose imagery your tiles are based I believe, would probably be welcome.

:slightly_smiling_face:

**Comment by naveenpf** [comment]
part of #36 

@planemad

**Comment by planemad** [comment]
Done
