### ISSUE TITLE
Wiki on Step by Step contribution

### ISSUE THREAD

**Issue by aniketmaithani** [osm-in/openstreetmap.in#3]
For "Newbies" I would like to create a quick start document for openstreetmap.in :) I would be happy to take this task as I am myself learning this whole process from scratch. We can have docs using MKDOCS or any other tools. 

Suggestions are welcome!

**Comment by planemad** [comment]
@aniketmaithani the Mapbox data team have put together exactly such a guid here: https://github.com/mapbox/mapping/wiki/Mapping-with-OpenStreetMap

If this works well we will add it to the main page.

**Comment by aniketmaithani** [comment]
Yes. Looks Good!
