### ISSUE TITLE
Website to aid in welcoming new mappers

### ISSUE THREAD

**Issue by naveenpf** [osm-in/openstreetmap.in#34]
Website to aid in welcoming new mappers

Sample :- welcome.osm.be/
Github :- https://github.com/osmbe/osm-welcome-belgium

Like Twinkle in wikipedia.

**Comment by planemad** [comment]
Great idea. If someone is willing to setup that php site, count me in for covering any server expense.

**Comment by naveenpf** [comment]
LCCWG tracking- https://gitlab.com/osmfoundation/lccwg/-/issues/8

Stefano (sabas; who made https://github.com/osmItalia/welcome-tool)
midgard (author of https://github.com/osmbe/osm-welcome-belgium)
OSMUS Spring Hackathon (https://github.com/kriscarle/wilcuma-api)

**Comment by naveenpf** [comment]
osmlab/osm-planning/issues/13

**Comment by naveenpf** [comment]
closing this. found a way for now.
