### ISSUE TITLE
Subdomain for Kerala Community

### ISSUE THREAD

**Issue by manojkmohan** [osm-in/openstreetmap.in#35]
For OpenStreetMap Kerala Community we are searching for a domain to setting up a landing page. is it possible to create subdomain http://kerala.openstreetmap.in ? @geohacker @planemad @naveenpf

**Comment by geohacker** [comment]
@manojkmohan no objections from me. I think the domain is managed by @satyaakam so you can contact him. I have just added him to this repo but you might have luck reaching him on OSM India telegram faster.

**Comment by manojkmohan** [comment]
Thanks @geohacker . @satyaakam also give positive response via Telegram channel.

After making a draft one, soon can share a url for domain pointing. and share the updates to community.

**Comment by manojkmohan** [comment]
Here is the to our developing site url.  http://osmkerala.github.io
Need to pointing from here http://kerala.openstreetmap.in 
Hope soon, in few days we can active the site in a shareable way.
Thanks.

**Comment by joicemjoseph** [comment]
> Here is the to our developing site url. http://osmkerala.github.io
> Need to pointing from here http://kerala.openstreetmap.in
> Hope soon, in few days we can active the site in a shareable way.
> Thanks.

I think it will be better to have https.

**Comment by manojkmohan** [comment]
Thanks Joice. 
@satyaakam can you please followup.

**Comment by satyaakam** [comment]
@manojkmohan i have just added entries in DNS lets wait for sometime for changes to reflect

**Comment by satyaakam** [comment]
The Subdomain is resolving to your Website we can close this issue now

**Comment by joicemjoseph** [comment]
yes, it is resolving. Forgot to report here. Thank you very much!

**Comment by manojkmohan** [comment]
Thanks @satyaakam & osm-in team. Happy to be part of the community. Hope we can mobilize some momentum.
