### ISSUE TITLE
Update homepage map to latest tiles

### ISSUE THREAD

**Issue by planemad** [osm-in/openstreetmap.in#36]
The existing map on the homepage https://openstreetmap.in/ is generated using outdated [mapbox-streets-v5](https://docs.mapbox.com/vector-tiles/reference/mapbox-streets-v5/) tiles that are no longer synced with OSM data https://github.com/osm-in/openstreetmap.in/issues/30

This should be updated to use the latest [mapbox-streets-v8](https://docs.mapbox.com/vector-tiles/reference/mapbox-streets-v8/) tiles that are synced with OSM.

**Comment by planemad** [comment]
Test site: http://osm-in.github.io/openstreetmap.in/

**Comment by naveenpf** [comment]
We are not bringing in multilingual in this version ?

**Comment by planemad** [comment]
> We are not bringing in multilingual in this version ?

At least for this task, it is to get a homepage map with updated OSM data. Will have to think about the best option for multingual features later.

**Comment by planemad** [comment]
[Style preview](https://api.mapbox.com/styles/v1/planemad/ckf4xcet7231819mm2e8njlca.html?fresh=true&title=copy&access_token=pk.eyJ1IjoicGxhbmVtYWQiLCJhIjoiemdYSVVLRSJ9.g3lbg_eN0kztmsfIPxa9MQ#4.45/22.82/82.67)

<img width="534" alt="Screen Shot 2020-09-22 at 1 35 04 AM" src="https://user-images.githubusercontent.com/126868/93847908-48721d00-fc76-11ea-907e-ba5d5b93efa0.png">

<img width="729" alt="Screen Shot 2020-09-22 at 1 33 57 AM" src="https://user-images.githubusercontent.com/126868/93847898-46a85980-fc76-11ea-8b52-87a38f17559f.png">
<img width="716" alt="Screen Shot 2020-09-22 at 1 33 29 AM" src="https://user-images.githubusercontent.com/126868/93847893-4445ff80-fc76-11ea-99e7-a25b1f43c86f.png">

**Comment by naveenpf** [comment]
State map with Ladhak .. superb ...

**Comment by planemad** [comment]
Demo site updated to include twitter feed and intro video.

<img width="1414" alt="Screen Shot 2020-10-04 at 1 56 48 AM" src="https://user-images.githubusercontent.com/126868/95008117-e0f88d80-05e4-11eb-94af-2ab157ace1de.png">

**Comment by naveenpf** [comment]
In this frame, can we add https://export.hotosm.org/en/v3/ ?
![image](https://user-images.githubusercontent.com/12662835/95008176-23e25180-0635-11eb-9c78-9f181431bc93.png)

**Comment by planemad** [comment]
@naveenpf done

**Comment by planemad** [comment]
New site is in the `master` branch https://github.com/osm-in/openstreetmap.in/tree/master

@geohacker @batpad whats the procedure to deploy this branch on https://openstreetmap.in/ ? Its time to take the old one down.

**Comment by naveenpf** [comment]
should we move to a new server ?  
@batpad  was suggesting that it was better to move new server, exclusively for OSM India.

**Comment by planemad** [comment]
Right now, we don't even need a server for the homepage since we can just utilize the github pages hosting https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site and not have to deal with any sysadmin stuff.

We probably need it for a custom tileserver, but it does not look like there are any concrete plans for that soon.

**Comment by geohacker** [comment]
I'm happy to deploy this on the server, but also feel free to setup the static site on Github. We can get Satya to point the domain here.

**Comment by planemad** [comment]
@geohacker For the immediate needs of openstreetmap.in, the static site works and eliminates all the sysadmin overhead. Any reason not to just use github pages for now?

**Comment by batpad** [comment]
> For the immediate needs of openstreetmap.in, the static site works and eliminates all the sysadmin overhead. Any reason not to just use github pages for now?

Let's *please* move to Github pages! Please let me know if I can help, but this should just need Satya to point the domain and doing some config in Github?

Will send a separate mail to the list following up on moving other openstreetmap.in resources off this server that @geohacker and I have been paying for and maintaining that really should be retired soon :-) - I'm very :+1: on moving the static site to Github pages.

**Comment by planemad** [comment]
👍 will coordinate with Satya

> that @geohacker and I have been paying for

May you both have more ❤️❤️❤️❤️ than 💰 spent.

**Comment by geohacker** [comment]
@planemad my recommendation would be use the jekyll build gh-pages deploy and wire it up as a Github Action https://github.com/marketplace/actions/jekyll-deploy-gh-pages - I'll do it this weekend and then we can have @satyaakam point the cname to the github DNS.

**Comment by satyaakam** [comment]
> > For the immediate needs of openstreetmap.in, the static site works and eliminates all the sysadmin overhead. Any reason not to just use github pages for now?
> 
> Let's _please_ move to Github pages! Please let me know if I can help, but this should just need Satya to point the domain and doing some config in Github?
> 
> Will send a separate mail to the list following up on moving other openstreetmap.in resources off this server that @geohacker and I have been paying for and maintaining that really should be retired soon :-) - I'm very  on moving the static site to Github pages.

@batpad make sense , how are you long time let chat one of these days !!

**Comment by naveenpf** [comment]
> Right now, we don't even need a server for the homepage since we can just utilize the github pages hosting https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site and not have to deal with any sysadmin stuff.
> 
> We probably need it for a custom tileserver, but it does not look like there are any concrete plans for that soon.

Then it is good. 
Only hit is OSM IN tasking manager.
KL subpage is also hosted in gh.

**Comment by planemad** [comment]
@geohacker @satyaakam lmk if i can support somehow.My assumption is that you can take care of this between the both of you.

**Comment by satyaakam** [comment]
@geohacker let me known where it should be pointing to , will make changes accordingly

**Comment by naveenpf** [comment]
@planemad @geohacker @satyaakam 

Very good response on twitter. 
https://twitter.com/osm_in/status/1328964927835566086

**Comment by planemad** [comment]
👏 congrats everyone!

Will make a new ticket to track setup for github actions for auto deploying changes.
