### ISSUE TITLE
Render District Boundary and Lok Sabha Constituencies Boundary 

### ISSUE THREAD

**Issue by naveenpf** [osm-in/openstreetmap.in#9]
District Boundary  
boundary=administrative
    admin_level=5

Lok Sabha Constituency 
    boundary=political
    political_division=1

**Comment by planemad** [comment]
@naveenpf districts sounds good :+1: 

Not so sure about constituencies as the boundaries do not coincide with districts and adds a bit of complexity.

**Comment by naveenpf** [comment]
@planemad should i close this ?

**Comment by planemad** [comment]
👍 district boundaries added.

One thing to note is that the boundaries comes from Mapbox data and not from OSM since it was very easy to implement.

We can open a seperate ticket about migrating to OSM based boundaries

**Comment by naveenpf** [comment]
that is fine.
